# Generated by Django 2.2.15 on 2021-01-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=128, unique=True)),
                ('passwd', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=128)),
                ('gtime', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='goods/')),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'verbose_name': '失物物品',
                'verbose_name_plural': '失物物品',
            },
        ),
    ]
