# Generated by Django 3.1.5 on 2021-01-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='gtype',
            field=models.CharField(default=False, max_length=128),
        ),
    ]
